/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemId = IDL.Nat;
export const CartItem = IDL.Record({ 'itemId' : ItemId, 'quantity' : IDL.Nat });
export const Cart = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
  'subtotal' : IDL.Nat,
});
export const Category = IDL.Variant({
  'desserts' : IDL.Null,
  'appetizers' : IDL.Null,
  'mainCourses' : IDL.Null,
  'drinks' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : ItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderId = IDL.Nat;
export const OrderSummaryItem = IDL.Record({
  'itemId' : ItemId,
  'name' : IDL.Text,
  'lineTotal' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const OrderSummary = IDL.Record({
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'items' : IDL.Vec(OrderSummaryItem),
  'subtotal' : IDL.Nat,
});
export const PlaceOrderResult = IDL.Variant({
  'ok' : OrderSummary,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([ItemId, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getMenuItem' : IDL.Func([ItemId], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrderSummary' : IDL.Func([], [IDL.Opt(OrderSummary)], ['query']),
  'placeOrder' : IDL.Func([], [PlaceOrderResult], []),
  'removeFromCart' : IDL.Func([ItemId], [], []),
  'updateCartItem' : IDL.Func([ItemId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemId = IDL.Nat;
  const CartItem = IDL.Record({ 'itemId' : ItemId, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
    'subtotal' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'desserts' : IDL.Null,
    'appetizers' : IDL.Null,
    'mainCourses' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : ItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderId = IDL.Nat;
  const OrderSummaryItem = IDL.Record({
    'itemId' : ItemId,
    'name' : IDL.Text,
    'lineTotal' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const OrderSummary = IDL.Record({
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'createdAt' : Timestamp,
    'orderId' : OrderId,
    'items' : IDL.Vec(OrderSummaryItem),
    'subtotal' : IDL.Nat,
  });
  const PlaceOrderResult = IDL.Variant({
    'ok' : OrderSummary,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([ItemId, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getMenuItem' : IDL.Func([ItemId], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrderSummary' : IDL.Func([], [IDL.Opt(OrderSummary)], ['query']),
    'placeOrder' : IDL.Func([], [PlaceOrderResult], []),
    'removeFromCart' : IDL.Func([ItemId], [], []),
    'updateCartItem' : IDL.Func([ItemId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };