/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart {
  'total' : bigint,
  'items' : Array<CartItem>,
  'subtotal' : bigint,
}
export interface CartItem { 'itemId' : ItemId, 'quantity' : bigint }
export type Category = { 'desserts' : null } |
  { 'appetizers' : null } |
  { 'mainCourses' : null } |
  { 'drinks' : null };
export type ItemId = bigint;
export interface MenuItem {
  'id' : ItemId,
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : bigint,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface OrderSummary {
  'status' : OrderStatus,
  'total' : bigint,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'items' : Array<OrderSummaryItem>,
  'subtotal' : bigint,
}
export interface OrderSummaryItem {
  'itemId' : ItemId,
  'name' : string,
  'lineTotal' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type PlaceOrderResult = { 'ok' : OrderSummary } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'addToCart' : ActorMethod<[ItemId, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCart' : ActorMethod<[], Cart>,
  'getMenuItem' : ActorMethod<[ItemId], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[Category], Array<MenuItem>>,
  'getOrderSummary' : ActorMethod<[], [] | [OrderSummary]>,
  'placeOrder' : ActorMethod<[], PlaceOrderResult>,
  'removeFromCart' : ActorMethod<[ItemId], undefined>,
  'updateCartItem' : ActorMethod<[ItemId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];